log:
  level: info
  file: "/tmp/mosdns.log"

# API 入口设置
api:
  http: ":9091"

include: []

plugins:
  # 缓存
  - tag: cache
    type: cache
    args:
      size: 768

  - args:
      concurrent: 2
      upstreams:
          - addr: https://dns.alidns.com/dns-query
            enable_http3: true
            dial_addr: 2400:3200::1
            tag: alidns1
          - addr: https://dns.alidns.com/dns-query
            enable_http3: true
            dial_addr: 2400:3200:baba::1
            tag: alidns2
    tag: fast_forward
    type: forward
      

  # 主要的运行逻辑插件
  # sequence 插件中调用的插件 tag 必须在 sequence 前定义，
  # 否则 sequence 找不到对应插件。
  - tag: main_sequence
    type: sequence
    args:
      - exec: $cache
      - exec: $fast_forward

  # 启动 udp 服务器。
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: ":5335"

  # 启动 tcp 服务器。
  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: ":5335"
